services:
  user-service:
    volumes:
      - ./user-service:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    command: sh -c "npx prisma migrate deploy && npx nodemon --legacy-watch --watch src --ext ts,js,json --exec ts-node src/index.ts"

  vehicle-service:
    volumes:
      - ./vehicle-service:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    command: sh -c "npx prisma migrate deploy && npx nodemon --legacy-watch --watch src --ext ts,js,json --exec ts-node src/index.ts"

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    command: npm run dev -- --host 0.0.0.0 --port 3000

